//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Modele.Jeu
{
	using Modele.Creation;
	using System;
	using System.Collections.Generic;
	using System.Linq;
    using System.Text;
    using System.Windows.Media;
    using System.Windows.Media.Imaging;
    using SmallWorldLib.GeneratedCode.Vue;

    /**
     * \class Nain
     * 
     * \brief Represents unites of type "Nain"
     * 
     */
	public class Nain : Unite
	{
        public static ImageBrush ICON = new ImageBrush(new BitmapImage(new Uri(@"..\..\Resources\dwarf.png", UriKind.Relative)));

		public override List<Tuple<int,int>> getChoixCases()
		{
			throw new System.NotImplementedException();
		}

        /**
         * \fn public Nain()
         * \brief constructor directly from superclass
         * 
         */
		public Nain() : base()
		{
            icon = ICON;
		}

        public override int deplacementPossible(int lig, int col)
        {
            Tuple<int, int> pos = Position;
            int res;
            if (carte.Cases[lig][col] == carte.Fabrique.Montagne && carte.Cases[pos.Item1][pos.Item2] == carte.Fabrique.Montagne)
                res = 1;
            else
                res = Math.Abs(pos.Item1 - lig) + Math.Abs(pos.Item2 - col);
            if (res <= deplacement && carte.Cases[lig][col] != carte.Fabrique.Eau)
                return res;
            else
                return -1;
        }

        public override void setBonusMalusPoints(bool on)
        {
            if (on)
            {
                carte.Fabrique.Foret.Points++;
                carte.Fabrique.Plaine.Points = 0;
            }
            else
            {
                carte.Fabrique.Plaine.setDefault();
                carte.Fabrique.Foret.setDefault();
            }
        }

	}
}

