//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Modele.Jeu
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <remarks>Poids-mouche</remarks>
	public class FabriqueCase : FabriqueCaseI
	{
		public virtual Desert desert
		{
			get;
			set;
		}

		public virtual Montagne montagne
		{
			get;
			set;
		}

		public virtual Plaine plaine
		{
			get;
			set;
		}

		public virtual Foret foret
		{
			get;
			set;
		}

		public virtual Eau eau
		{
			get;
			set;
		}

		public FabriqueCase()
		{
		}

	}
}

