//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Modele.Jeu
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <remarks>Poids-mouche</remarks>
	public class FabriqueCase : FabriqueCaseI
	{
		private Desert desert;
        public Desert Desert
		{
            get
            {
                if (desert == null)
                    desert = new Desert();
                return desert;
            }
		}

        private Montagne montagne;
        public Montagne Montagne
		{
			get
            {
                if (montagne == null)
                    montagne = new Montagne();
                return montagne;
            }
		}

        private Plaine plaine;
        public Plaine Plaine
		{
			get
            {
                if (plaine == null)
                    plaine = new Plaine();
                return plaine;
            }
		}

        private Foret foret;
        public Foret Foret
		{
			get
            {
                if (foret == null)
                    foret = new Foret();
                return foret;
            }
		}

        private Eau eau;
        public Eau Eau
		{
			get
            {
                if (eau== null)
                    eau = new Eau();
                return eau;
            }
		}

		public FabriqueCase()
		{
		}

	}
}

