//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Modele.Jeu
{
	using Modele.Creation;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface JoueurI 
	{
		void passerMain();

		int nbUnitesJouables();

		void passerMain(JoueurI adversaire);

		bool aVaincu(JoueurI adversaire);

		void fin();

        bool unitesSelectionnables(int lig, int col);

	}
}

