//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Modele.Jeu
{
	using Modele.Creation;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using Vue.Jeu;

	public class Joueur : JoueurI
	{
		private int points
		{
			get;
			set;
		}

		private bool premier
		{
			get;
			set;
		}

		public virtual IEnumerable<Unite> unites
		{
			get;
			set;
		}

		public Joueur(List<UniteI> unites)
		{
		}

		public virtual void passerMain()
		{
			throw new System.NotImplementedException();
		}

		public virtual int nbUnitesJouables()
		{
			throw new System.NotImplementedException();
		}

		public virtual void passerMain(JoueurI adversaire)
		{
			throw new System.NotImplementedException();
		}

		public virtual bool aVaincu(JoueurI adversaire)
		{
			throw new System.NotImplementedException();
		}

		public virtual void fin()
		{
			throw new System.NotImplementedException();
		}

		public virtual bool unitesSelectionnables()
		{
			throw new System.NotImplementedException();
		}

	}
}

