//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Modele.Jeu
{
	using Modele.Creation;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Nain : Unite
	{
		public override List<Entry<int,int>> getChoixCases()
		{
			throw new System.NotImplementedException();
		}

		public Nain(CarteI carte)
		{
		}

		public override int rapporterPoints()
		{
			throw new System.NotImplementedException();
		}

	}
}

