//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Modele.Jeu
{
	using Modele.Creation;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Partie : PartieI
	{
		private int nombreTours;
        public virtual int NombreTours
		{
			get;
			set;
		}

        private List<JoueurI> joueurs;
		public virtual List<JoueurI> Joueurs
		{
			get;
			set{if(value.Count == 2) joueurs = value;}
		}

        private CarteI carte;
		public virtual CarteI Carte
		{
			get;
			set;
		}

        /**
         * \fn public Partie(List<JoueurI> joueurs, int nbTours, CarteI carte)
         * \brief Constructor of a party
         * 
         * param[in] joueurs : players
         * param[in] nbTours : number of rounds
         * param[in] carte : map
         * 
         */
        public Partie(List<JoueurI> joueurs, int nbTours, CarteI carte)
		{
            this.joueurs = joueurs;
            this.nombreTours = nbTours;
            this.carte = carte;
		}

		public virtual void start()
		{
			throw new System.NotImplementedException();
		}

		public virtual void afficherUnites(List<UniteI> unites)
		{
			throw new System.NotImplementedException();
		}

		public virtual JoueurI determinerGagnant()
		{
			throw new System.NotImplementedException();
		}

	}
}

