//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Modele.Jeu
{
	using Modele.Creation;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using Vue;

	public abstract class Unite : UniteI
	{
		protected virtual int vie
		{
			get;
			set;
		}

		protected virtual int deplacement
		{
			get;
			set;
		}

		public virtual VueUnite vueUnite
		{
			get;
			set;
		}

		public virtual Etat etat
		{
			get;
			set;
		}

		public virtual void selectionner()
		{
			throw new System.NotImplementedException();
		}

		public virtual int verifPointsDeplacement()
		{
			throw new System.NotImplementedException();
		}

		public virtual void deplacer(int lig, int col)
		{
			throw new System.NotImplementedException();
		}

		public virtual void attaquer(int lig, int col)
		{
			throw new System.NotImplementedException();
		}

		public virtual List<Entry<int,int>> getChoixCases()
		{
			throw new System.NotImplementedException();
		}

		public virtual List<Entry<int,int>> deplacementsPossibles()
		{
			throw new System.NotImplementedException();
		}

		public virtual void engagement(UniteI defenseur)
		{
			throw new System.NotImplementedException();
		}

		public virtual int getNbTours(UniteI defenseur)
		{
			throw new System.NotImplementedException();
		}

		public virtual UniteI combat(UniteI defenseur)
		{
			throw new System.NotImplementedException();
		}

		public Unite(CarteI carte)
		{
		}

		public virtual void afficher()
		{
			throw new System.NotImplementedException();
		}

		public abstract int rapporterPoints();

	}
}

