//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Interfaces.Modele.Jeu
{
	using Interfaces.Modele;
    using Interfaces.Modele.Jeu.Unit;
    using Implementation.Modele.Jeu.Unit;
    using Implementation.Modele.Jeu;
	using Interfaces.Modele.Creation;
    using Interfaces.Vue;
	using System;
    using System.Collections;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Wrapper;
    using System.ComponentModel;

	public interface CarteI : INotifyPropertyChanged
	{
        CarteWrapper CarteW
        {
            get;
        }

        List<List<int>> CodeCases
        {
            get;
            set;
        }

        int Dim
        {
            get;
            set;
        }

        FabriqueCaseI Fabrique
        {
            get;
            set;
        }

        List<List<CaseI>> Cases
        {
            get;
        }

        UniteI Selected
        {
            get;
            set;
        }

        //legions placed on the map
        List<LegionI> Legions
        {
            get;
            set;
        }

        //Temporary legion added recently which is to be shown
        LegionI TmpLegion
        {
            get;
        }

        /// <summary>
        /// the method give a list of all the positions which are ajacents to a unit
        /// </summary>
        /// <param name="unite"> unit of which the ajacent cases are to be given </param>
        /// <returns> list of all the adjacents positions </returns>
		List<Tuple<int, int>> getListeAdjacents(UniteI unite);

		void deplacer(UniteI unite, int lig, int col);

		bool isEmpty(int lig, int col);

        VueCaseI makeView(int l, int c);

        LegionI getLegion(int lig, int col);

        void ajouterLegion(LegionI legion);

        void generateCases();

        void linkJoueurs(List<Joueur> joueurs);

        void suggerer(int x, int y);
	}
}

