//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Interfaces.Modele.Jeu
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Implementation.Modele.Jeu;

	public interface FabriqueCaseI 
	{
        Desert Desert
        {
            get;
        }

        Montagne Montagne
        {
            get;
        }

        Plaine Plaine
        {
            get;
        }

        Foret Foret
        {
            get;
        }

        Eau Eau
        {
            get;
        }
	}
}

