//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Interfaces.Modele.Jeu
{
	using Implementation.Modele.Creation;
    using Implementation.Modele.Jeu;
    using Implementation.Modele.Jeu.Unit;
	using System;
	using System.Collections.Generic;
	using System.Linq;
    using System.Text;
    using System.ComponentModel;

	public interface JoueurI : INotifyPropertyChanged
	{
        int Points
        {
            get;
            set;
        }

        //instances of Unite that are in the current instance of Joueur army
        List<Unite> Unites
        {
            get;
            set;
        }

        bool Turn
        {
            get;
            set;
        }

        //Number of units which can't be played
        int NbUnitesNonJouables
        {
            get;
            set;
        }

        //maximum number of units in the army
        int NbMaxUnites
        {
            get;
        }

        //name of the player
        string Nom
        {
            get;
            set;
        }

		void passerMain(JoueurI adversaire);
	}
}

