//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Modele.Creation
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Modele.Jeu;

	public class FabriqueGaulois : FabriqueUnite
	{
		public virtual List<Gaulois> fabriquer(CarteI carte)
		{
			List<Gaulois> res = new List<Gaulois>();
            for (int i = 0; i < nombre; i++)
                res.Add(new Gaulois(carte));
            return res;
		}

		public FabriqueGaulois()
		{
		}

	}
}

