//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Modele.Creation
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Modele.Jeu;

	public class FabriqueViking : FabriqueUnite
	{
		public virtual List<Viking> fabriquer(CarteI carte)
		{
            List<Viking> res = new List<Viking>();
            for (int i = 0; i < nombre; i++)
                res.Add(new Viking(carte));
            return res;
		}

		public FabriqueViking()
		{
		}

	}
}

