//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Modele.Creation
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Modele.Jeu;

	public class FabriqueNain : FabriqueUnite
	{
		public virtual List<Nain> fabriquer(CarteI carte)
		{
            List<Nain> res = new List<Nain>();
            for (int i = 0; i < nombre; i++)
                res.Add(new Nain(carte));
            return res;
		}

		public FabriqueNain()
		{
		}

	}
}

