//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Modele.Creation
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Modele.Jeu;

	/// <remarks>Fabrique</remarks>
	public abstract class FabriqueUnite : FabriqueUniteI
	{

        protected int nombre;
		public int Nombre
		{
			get;
			set;
		}

		public abstract List<UniteI> fabriquer(CarteI carte);

		public FabriqueUnite()
		{
		}

	}
}

