//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Modele.Creation
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Modele.Jeu;

	public interface FabriqueI<T> where T : UniteI
	{
<<<<<<< HEAD
		List<T> fabriquer();
=======
        int Nombre
        {
            get;
            set;
        }

        List<UniteI> Products
        {
            get;
            set;
        }

		void fabriquer();
>>>>>>> 0575a4ed3ffb6ad26bfdcf5d2d20ffb19cbaf4df
        void defineNbProducts(int nombre);
        int nbProducts();
	}
}

