//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Modele.Creation
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Modele.Jeu;
    using Modele.Jeu.Unit;

    /**
     * \class Fabrique<T> where T : Unite, new()
     * \brief generic class used to produce units of the specified type T
     * 
     */
    public class Fabrique<T> : FabriqueI where T : UniteI, new()
	{

        protected int nombre;
		public int Nombre
		{
            get { return nombre; }
            set { nombre = value; }
		}

        protected List<UniteI> products;
        public List<UniteI> Products
        {
            get { return products; }
            set { products = value; }
        }


        /**
         * \fn Fabrique()
         * \brief default constructor
         * 
         */
        public Fabrique()
        {
        }

		public virtual void fabriquer()
		{
			products = new List<UniteI>();
            for (int i = 0; i < nombre; i++)
            {
                UniteI u = new T();
                products.Add(u);
                u.Automate = new AutomateUnite(u);
            }
		}

	}
}

