//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Modele.Creation
{
	using Modele.Jeu;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using Modele.Jeu;

	/// <remarks>
	/// Singleton
	/// 
	/// </remarks>
	public class GameInitiator : GameInitiatorI
	{
		private virtual MonteurPartieI monteurPartie
		{
			get;
			set;
		}

		private virtual PartieI partie
		{
			get;
			set;
		}

		public virtual FabriqueUniteI fabriqueUnite1
		{
			get;
			set;
		}

		public virtual FabriqueUniteI fabriqueUnite2
		{
			get;
			set;
		}

		private GameInitiator()
		{
		}

		public virtual void creerPartie()
		{
            ((MonteurPartie)monteurPartie).FabriqueUnite1 = fabriqueUnite1;
            ((MonteurPartie)monteurPartie).FabriqueUnite2 = fabriqueUnite2;
            CarteI carte = monteurPartie.makeCarte();
            List<JoueurI> joueurs = monteurPartie.makeJoueurs(carte);
		}

	}
}

