//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Modele.Creation
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface GameInitiatorI 
	{
<<<<<<< HEAD
		void creerPartie();
=======
        MonteurPartieI MonteurPartie
        {
            get;
            set;
        }

        List<FabriqueI> FabriquesUnite
        {
            get;
            set;
        }

		PartieI creerPartie();
>>>>>>> 0575a4ed3ffb6ad26bfdcf5d2d20ffb19cbaf4df

	}
}

