//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Modele.Creation
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Modele.Jeu;

    /// <remarks>
    /// Singleton
    /// </remarks>
    /// <summary>
    /// used to configurate the game (peoples, size of the map, number of turns, number of units by army)
    /// </summary>
	public interface GameInitiatorI 
	{
        //builder : determines the type of the game (size of the map, number of rounds, ...)
        MonteurPartieI MonteurPartie
        {
            get;
            set;
        }

        //unit factories
        List<FabriqueI> FabriquesUnite
        {
            get;
            set;
        }

        /// <summary>
        /// creates the intern representation of the game
        /// delegates the work to its attributes : the game builder and unit factory
        /// </summary>
        /// <returns> representation of the game </returns>
		PartieI creerPartie();

	}
}

