//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Modele.Creation
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Modele.Jeu;

	public class MonteurPartieNormale : MonteurPartie
	{
        public List<FabriqueUniteI> FabriquesUnite
        {
            get;
            set
            {
                base.FabriquesUnite = value;
                if (value.Count == 2)
                {
                    foreach (FabriqueUniteI fu in value)
                        fu.defineNbProducts(8);
                }
            }
        }

        /**
         * \fn public override CarteI makeCarte(List<JoueurI> joueurs)
         * \brief only call the constructor of a "CarteI" implementation
         * 
         * The map generated places the players. Its dimension is 15
         * 
         * param[in, out] joueurs : parameters of the constructor of the map
         * 
         */
		public override CarteI makeCarte(List<JoueurI> joueurs)
		{
			return new Carte(15, joueurs);
		}

		public MonteurPartieNormale()
		{
            nbTours = 30;
		}

	}
}

