//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Modele.Creation
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Modele.Jeu;
    using Modele.Jeu.Joueur;

	/// <remarks>Monteur</remarks>
	/// <remarks>Stratégie : difficultée de la partie</remarks>
	public abstract class MonteurPartie : MonteurPartieI
	{

        protected int nbTours
        {
            get;
            set;
        }

        protected FabriqueUniteI fabriqueUnite1;
		public FabriqueUniteI FabriqueUnite1
		{
			get;
			set;
		}

        protected FabriqueUniteI fabriqueUnite2;
        public FabriqueUniteI FabriqueUnite2
        {
            get;
            set;
        }

		public abstract CarteI makeCarte();

		public virtual List<JoueurI> makeJoueurs()
		{
			List<JoueurI> res = new List<JoueurI>();
            res.Add(new Joueur(fabriqueUnite1.fabriquer()));
            res.Add(new Joueur(fabriqueUnite2.fabriquer()));
            return res;
		}

        public void setFabriqueUnite(int i, FabriqueUniteI fu)
        {
            switch (i)
            {
                case 1:
                    this.FabriqueUnite1 = fu;
                    break;
                case 2:
                    this.FabriqueUnite2 = fu;
                    break;
                default:
                    break;
            }
        }

		public MonteurPartie()
		{
		}

	}
}

