//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Modele.Creation
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Modele.Jeu;
    using Modele.Jeu.Joueur;

    /// <summary>
    /// Builder of a demonstration game : 8 units by army, map of 15 X 15 cases, 30 rounds
    /// </summary>
	public class MonteurPartieNormale : MonteurPartie
	{
        //unit factories
        public override List<FabriqueI> FabriquesUnite
        {
            set
            {
                base.FabriquesUnite = value;
                if (value.Count == 2)
                {
                    //we force the number of units to 8
                    foreach (FabriqueI fu in value)
                        fu.Nombre = 8;
                }
            }
        }

        /// <summary>
        /// The method produces the map, depending on the selected parameters.
        /// The players must be associated to the produced map.
        /// The map contains 15 X 15 cases
        /// </summary>
        /// <param name="joueurs"> players of the game </param>
        /// <returns> map of the game </returns>
		public override CarteI makeCarte(List<Joueur> joueurs)
		{
			return new CarteCS(15, joueurs);
		}

        /// <summary>
        /// default constructor
        /// the number of rounds is initilized to 30
        /// </summary>
		public MonteurPartieNormale()
            : base()
		{
            nbTours = 30;
		}

	}
}

