//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Modele.Creation
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Modele.Jeu;
    using Modele.Jeu.Joueur;

    /// <summary>
    /// Builder of a demonstration game : 4 units by army, map of 5X5 cases, 5 rounds
    /// </summary>
	public class MonteurPartieDemo : MonteurPartie
	{

        //unit factories
        public override List<FabriqueI> FabriquesUnite
        {
            set
            {
                base.FabriquesUnite = value;
                if (value.Count == 2)
                {
                    //we force the number of units to 4
                    foreach (FabriqueI fu in value)
                        fu.Nombre = 4;
                }
            }
        }

        /// <summary>
        /// The method produces the map, depending on the selected parameters.
        /// The players must be associated to the produced map.
        /// The map contains 5X5 cases
        /// </summary>
        /// <param name="joueurs"> players of the game </param>
        /// <returns> map of the game </returns>
		public override CarteI makeCarte(List<Joueur> joueurs)
		{
            return new CarteCS(5, joueurs);
		}

        /// <summary>
        /// default constructor
        /// the number of rounds is initilized to 5
        /// </summary>
		public MonteurPartieDemo()
            : base()
		{
            nbTours = 5;
		}

	}
}

