//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Modele.Creation
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Modele.Jeu;
    using Modele.Jeu.Joueur;

	/// <remarks>Monteur</remarks>
	/// <remarks>Stratégie : difficultée de la partie</remarks>
	public abstract class MonteurPartie : MonteurPartieI
	{

        protected int nbTours;
        public int NbTours
        {
            get;
            set;
        }

        protected List<Fabrique<UniteI>> fabriquesUnite;
        public List<Fabrique<UniteI>> FabriquesUnite
		{
			get;
            set
            {
                if (value.Count == 2)
                {
                    fabriquesUnite = value;
                }
            }
		}

		public virtual List<JoueurI> makeJoueurs()
		{
			List<JoueurI> res = new List<JoueurI>();
            res.Add(new Joueur(fabriquesUnite[0].fabriquer()));
            res.Add(new Joueur(fabriquesUnite[1].fabriquer()));
            return res;
		}

        public void defineFabriqueUnite(List<FabriqueUniteI> fu)
        {
            this.FabriquesUnite = fu;
        }

		public MonteurPartie()
		{
		}

        public abstract CarteI makeCarte(List<JoueurI> joueurs);

	}
}

