//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Modele.Creation
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Modele.Jeu;
    using Modele.Jeu.Joueur;

	public interface MonteurPartieI 
	{
<<<<<<< HEAD
		JoueurI creerJoueur(List<UniteI> unites);
=======
        int NbTours
        {
            get;
            set;
        }

        List<FabriqueI> FabriquesUnite
        {
            get;
            set;
        }
>>>>>>> 0575a4ed3ffb6ad26bfdcf5d2d20ffb19cbaf4df

		CarteI makeCarte(List<JoueurI> joueurs);

		List<JoueurI> makeJoueurs();

        void defineFabriqueUnite(List<FabriqueUniteI> fu);

	}
}

